[package]
name = "sycamore-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-console = "0.3.0"
sycamore = { version = "0.9.0-beta.2" }
sycamore-router = "0.9.0-beta.2"
sycamore-seoul = { path="../sycamore-seoul" }